on:
    workflow_dispatch:
    push:
        branches:
            - main
            - deploy

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v4
            ## Buildx is needed for caching
            -
                name: Set up Buildx
                uses: docker/setup-buildx-action@v2
            -
                name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -
                run: ./deploy/build.sh

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v4
            -
                name: Install SSH key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.SWARM_SSH_PRIVATE_KEY }}
                    known_hosts: server.zenmo.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ1E4LUG22qgzc8U7oNYGWCn0cyA31+iyX2pck9wcPMS
            -
                name: docker context create
                run: docker context create zenmoswarm --docker "host=ssh://root@server.zenmo.com"
            -
                run: docker context use zenmoswarm
            -
                run: ./deploy/deploy.sh
